#!/usr/bin/env python3
"""Generate all 30 culinary AI apps."""

APPS = [
    ("ai-ingredient-swap", "145deg,60%,50%", "green", "🔄", "AI Ingredient Swap", "Recipe allergen/diet modifier", "e.g. Replace eggs in brownies for vegan, or swap wheat flour for gluten-free...", "You are a professional culinary AI specializing in ingredient substitutions for allergen-free, diet-specific, and flavor-optimized cooking."),
    ("ai-wine-pairing", "270deg,65%,55%", "violet", "🍷", "AI Wine Pairing", "Wine & food pairing advisor", "e.g. Wine pairing for grilled ribeye with roasted vegetables, or best wines for a Thai curry dinner...", "You are a sommelier AI assistant specializing in wine and food pairings."),
    ("ai-meal-prep", "0deg,65%,50%", "red", "🥗", "AI Meal Prep", "Macro-based meal prep planner", "e.g. 5-day meal prep for 200g protein, 150g carbs, 60g fat per day. No pork...", "You are a nutrition and meal prep planning AI. Generate weekly macro-based meal plans."),
    ("ai-knife-skills", "25deg,70%,55%", "orange", "🔪", "AI Knife Skills", "Knife skills & technique guide", "e.g. How to julienne carrots, brunoise onions, and chiffonade basil with proper technique...", "You are a culinary instructor specializing in knife skills and professional cutting techniques."),
    ("ai-sous-vide", "220deg,60%,55%", "blue", "🌡️", "AI Sous Vide", "Sous vide parameter calculator", "e.g. Sous vide parameters for a 2-inch ribeye, medium-rare, 1-3 hour window...", "You are a sous vide precision cooking expert. Calculate time, temperature, and finishing methods."),
    ("ai-fermentation", "85deg,65%,50%", "lime", "🦠", "AI Fermentation", "Fermentation starter guide", "e.g. How to start a vegetable fermentation with cabbage and carrots, 2% salt brine...", "You are a fermentation specialist. Guide users through lactic acid fermentation, SCOBY creation, and koji cultivation."),
    ("ai-baking-ratio", "175deg,55%,45%", "teal", "🥐", "AI Baking Ratio", "Baker's percentage calculator", "e.g. Baker's percentages for sourdough bread with 70% hydration and 20% levain...", "You are a professional baker specializing in baker's percentages and formula ratios."),
    ("ai-food-cost", "305deg,60%,60%", "pink", "💰", "AI Food Cost", "Food cost & menu pricing", "e.g. Food cost calculation for chicken piccata with 35% food cost target, 4-oz portion...", "You are a restaurant cost analyst. Calculate food costs, plate costs, and menu pricing with ideal margins."),
    ("ai-flavor-wheel", "265deg,55%,50%", "purple", "🎡", "AI Flavor Wheel", "Flavor profile visualizer", "e.g. Analyze the flavor profile of miso paste and show me the complete flavor wheel breakdown...", "You are a flavor chemistry expert. Analyze ingredients and dishes using the six basic tastes and beyond."),
    ("ai-sauce-recipes", "200deg,45%,45%", "slate", "🫕", "AI Sauce Recipes", "Sauce & condiment vault", "e.g. Classic béchamel sauce, or how to make a quick pan sauce for steak...", "You are a sauce specialist. Provide detailed recipes and techniques for mother sauces and derivatives."),
    ("ai-seasonal-menu", "0deg,60%,50%", "red", "🌿", "AI Seasonal Menu", "Farm-to-table seasonal menu", "e.g. Create a 4-course spring dinner menu using what's in season in the Pacific Northwest...", "You are a farm-to-table chef. Create seasonal menus based on local, in-season ingredients."),
    ("ai-coffee-brewing", "45deg,75%,55%", "yellow", "☕", "AI Coffee Brewing", "Coffee extraction guide", "e.g. Optimal grind size, water temp, and brew time for pour-over with light roast Ethiopian beans...", "You are a specialty coffee expert. Guide extraction parameters for different brewing methods."),
    ("ai-kitchen-gear", "340deg,55%,55%", "rose", "🍳", "AI Kitchen Gear", "Kitchen equipment advisor", "e.g. Best knife set for a home cook, or which stand mixer for bread baking under $500...", "You are a kitchen equipment consultant. Recommend tools, appliances, and gear for specific cooking needs."),
    ("ai-spice-blend", "125deg,55%,45%", "emerald", "🌿", "AI Spice Blend", "Custom spice blend composer", "e.g. Create a custom garam masala blend for a mild curry, or a jerk seasoning for chicken...", "You are a spice blending expert. Compose custom spice blends with ratios and flavor notes."),
    ("ai-brine-cure", "185deg,60%,55%", "cyan", "🧂", "AI Brine & Cure", "Brine & cure calculator", "e.g. Wet brine for a 5lb turkey, or dry cure for proscuitto-style ham over 14 days...", "You are a charcuterie expert. Calculate brines, cures, and smoking schedules for meat preservation."),
    ("ai-vegan-protein", "235deg,55%,55%", "indigo", "🌱", "AI Vegan Protein", "Vegan protein analyzer", "e.g. Complete protein combinations for a vegan athlete needing 120g protein per day...", "You are a vegan nutrition specialist. Analyze plant-based protein sources and meal combinations."),
    ("ai-food-storage", "165deg,55%,45%", "cyan", "🧊", "AI Food Storage", "Food storage optimizer", "e.g. How to store fresh herbs, or best methods for freezing cooked grains and beans...", "You are a food preservation expert. Provide storage guidelines for pantry, refrigerator, and freezer."),
    ("ai-sourdough", "215deg,45%,55%", "gray-blue", "🍞", "AI Sourdough", "Sourdough starter monitor", "e.g. My sourdough starter is 5 days old, not rising. How do I feed and maintain it?", "You are a sourdough baking expert. Guide starter maintenance, fermentation, and baking schedules."),
    ("ai-cuisine-deep", "0deg,65%,50%", "red", "🌏", "AI Cuisine Deep Dive", "Cultural cuisine deep dive", "e.g. History and key techniques of Sichuan cuisine, or essential elements of Japanese kaiseki...", "You are a culinary cultural historian. Provide deep dives into world cuisines, techniques, and traditions."),
    ("ai-molecular", "270deg,65%,55%", "violet", "🧪", "AI Molecular Gastronomy", "Molecular gastronomy translator", "e.g. How to make agar caviar, or reverse spherification of watermelon juice...", "You are a molecular gastronomy chef. Explain and guide advanced culinary techniques and transformations."),
    ("ai-bbq-calculator", "85deg,65%,50%", "lime", "🔥", "AI BBQ Calculator", "BBQ temperature controller", "e.g. Smoking schedule for a 12lb pork shoulder at 225°F, or reverse sear for prime rib...", "You are a BBQ pitmaster. Calculate temperatures, times, and techniques for smoked and grilled meats."),
    ("ai-food-photo", "25deg,70%,55%", "orange", "📸", "AI Food Photography", "Food photography recipe card", "e.g. Create a beautiful recipe card for mushroom risotto with plating notes for food photography...", "You are a food stylist and photographer. Create recipe cards with plating notes and styling tips."),
    ("ai-kombucha", "220deg,60%,55%", "blue", "🍵", "AI Kombucha", "Kombucha brewing helper", "e.g. First ferment timeline for 1-gallon batch, or second ferment with fruit flavors...", "You are a kombucha brewing specialist. Guide SCOBY maintenance, fermentation schedules, and flavoring."),
    ("ai-nutrition-label", "175deg,55%,45%", "teal", "🏷️", "AI Nutrition Label", "Food label decoder", "e.g. Decode this nutrition label and explain what each value means for my diet...", "You are a nutrition facts analyst. Decode and explain food labels, macros, and micronutrients."),
    ("ai-bread-ferment", "305deg,60%,60%", "pink", "🌾", "AI Bread Ferment", "Bread fermentation planner", "e.g. Plan a cold-retard schedule for a country loaf over 3 days, with preferment options...", "You are a bread fermentation expert. Plan schedules for bulk ferment, proofing, and cold retard."),
    ("ai-shu-compare", "265deg,55%,50%", "purple", "🌶️", "AI Spice Heat Compare", "Spice heat level comparator", "e.g. Compare heat levels and flavors of ghost pepper vs Carolina reaper vs habanero...", "You are a chili and spice expert. Compare heat levels (SHU), flavors, and best uses of chilies."),
    ("ai-pantry-list", "200deg,45%,45%", "slate", "🗃️", "AI Pantry List", "Pantry essentials optimizer", "e.g. Stock a well-equipped pantry for Mediterranean cooking, or Japanese pantry essentials...", "You are a pantry planning expert. Create comprehensive pantry lists organized by cuisine and purpose."),
    ("ai-dumpling-calc", "0deg,60%,50%", "red", "🥟", "AI Dumpling Calculator", "Dumpling & filling calculator", "e.g. Calculate filling for 50 dumplings, or best pork-to-cabbage ratio for Shanghai-style dumplings...", "You are a dumpling master. Calculate portions, ratios, and provide filling recipes for various dumpling styles."),
    ("ai-slow-cooker", "45deg,75%,55%", "yellow", "🍲", "AI Slow Cooker", "Slow cooker dump meal planner", "e.g. 8-hour slow cooker beef stew for 4 people, or dump-and-go chicken tacos...", "You are a slow cooker specialist. Create dump-and-go meal plans optimized for slow cooker timing and texture."),
    ("ai-menu-writing", "340deg,55%,55%", "rose", "📋", "AI Menu Writing", "Restaurant menu writer", "e.g. Write a 5-item prix fixe menu for an Italian restaurant with elegant descriptions...", "You are a restaurant menu copywriter. Write compelling, appetizing menu descriptions that drive sales."),
]

for app in APPS:
    name, hsl, color_name, icon, title, desc, placeholder, system = app
    print(f"{icon} {name}")
